placeholders:
    view_content_data_additional_information:
        items:
            demacmedia_trackedevents_view: ~
items:
    demacmedia_trackedevents_view:
        template: DemacMediaTrackedEventsUserBundle:TrackedEvents:events.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_magento.entity.customer.class%)

